version: '3'

services: 
  microservicesb:
    image: rafaelfs81/microservice-b:latest
    ports:
      - 9091:9091

  nginx:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html/
    ports:
      - 8080:80
      